### PR TITLE
Add generic function call syntax.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by rtsuk** [comment]
This change make the behavior of the navigation menu worse than before, as demonstrated by the before and after pictures below. Is there some way to make sure that function calls aren't interpreted as function definitions?

before
after

**Comment by rtsuk** [comment]
Also, what new feature or behavior are you aiming at with this change?

**Comment by reitermarkus** [comment]
I changed it to `support.class.rust` in order not to add entries to the navigation menu.

This adds syntax highlighting for enums/structs (`Type`) and for the “turbofish” (`::func<f64>`), which are currently show in the default text color.
```rust
Type::func<f64>()
```

**Comment by rtsuk** [comment]
LGTM. I don't know if @carols10cents wants me to merge changes without her taking a look so let's see if she weighs in.

**Comment by infininight** [comment]
Excluding items from the symbol list can be done on a very granular basis, pick the best scope for the item and then you can just exclude it. To do this you want to just add a suffix to it to make the scope unique and make a preference item with the value of:

```
{	showInSymbolList = :false; }
```

And a scope of `source.rust scope.name`.

**Comment by reitermarkus** [comment]
Thanks, the Ruby bundle also uses `support.class` for class names outside of the class definition, so in this case it is not needed to exclude them.

**Comment by reitermarkus** [comment]
@rtsuk, can you merge this now? Thanks!

**Comment by carols10cents** [comment]
@rtsuk if you approve of this, feel free to merge :)

**Comment by reitermarkus** [comment]
👍

**Pull request merged**
