### PR TITLE
Miscellaneous TextMate Changes

### PR DESCRIPTION
**Pull request by infininight**
After talking with you on twitter the other day I added the bundle to my review list to be added to the bundle installer. Did a review of the bundle mostly in regard to TextMate conventions and new features included in 2.0, nothing really Rust specific.

Made the these changes over the last couple days and just rebased on top of the current state. Ask if you have any questions about any of these changes or any TextMate questions in general.

A few comments and questions left after looking over the bundle:

* For single line snippets half end in a newline, half do not. We don't have any standard for this really, but should be consistant inside the bundle.
* The shortcuts for `Compile`/`Compile With Tests` are non-standard, generally we like to keep these to some combination of R/B and modifier keys. Compile (⇧⌘C) currently conflicts with Go → Computer.
* Question on cargo: Once a project is using cargo will those commands always be used and will a `Cargo.toml` file always be present at the project root?
* Should `Compile` be changed to Build to be consistant with `Cargo Build` or is there a reason for the terminology difference?
* `Compile`/`Compile With Tests` both only save the current document, the other related commands save all modified documents, an oversight?

### CODE REVIEW

**Comment by carols10cents** [comment]
This is awesome feedback and great changes, thank you so much!!!!! :heart: :heart: :heart: 

> For single line snippets half end in a newline, half do not. We don't have any standard for this really, but should be consistant inside the bundle.

I will totally clean this up! I haven't done a full audit to make code style consistent yet; this is a good time :)

> The shortcuts for Compile/Compile With Tests are non-standard, generally we like to keep these to some combination of R/B and modifier keys. Compile (⇧⌘C) currently conflicts with Go → Computer.

I will totally change that, I clearly have no idea what i'm doing on that front.

> Question on cargo: Once a project is using cargo will those commands always be used and will a Cargo.toml file always be present at the project root?

Yup! Cargo.toml is kind of like a Gemfile.

> Should Compile be changed to Build to be consistant with Cargo Build or is there a reason for the terminology difference?

So "Compile" was there before, and probably what most people would call what you do when you just run "rustc", but the cargo command is "cargo build". So the difference is an inconsistency in rust terminology :-/ I'm totally fine with changing Compile to Build, it might bother some people but oh well :)

> Compile/Compile With Tests both only save the current document, the other related commands save all modified documents, an oversight?

Not really, cargo compiles all the files in your current project, but the Compile/Compile With Tests commands will only compile the current file... how do other bundles handle this?

**Comment by infininight** [comment]
> I will totally change that, I clearly have no idea what i'm doing on that front.

One big feature we added recently has made finding available shortcuts easier in two ways:

In `Select Bundle Item` use ⌘3 to enable it to search all scopes (or use gear menu), you can then search for named items in all scopes to get an idea what similar items give their shortcut.

The even handier item is using the same but also switching to key equivalent search (⌘2). This will let you enter a shortcut and see what bundle items claim this shortcut, to see if there are any conflicts. The big thing added to this recently is that it lists all menu items as well, very handy for catching conflicts.

> Yup! Cargo.toml is kind of like a Gemfile.

So the fact that it is required is great news, I'll get cargo added to the build systems we add a scope for. This means anytime a project is open that has a `Cargo.toml` file in it's root there will be a new scope added. This means you can use it for triggering commands. Thusly you can, if desired, use the same shortcuts for `Run` and `Cargo Run` with the presence of the scope picking the winner.

> I'm totally fine with changing Compile to Build, it might bother some people but oh well :)

Your choice there, the only real benefit with the word build is that it syncs up mentally with using B in the shortcut.

> Not really, cargo compiles all the files in your current project, but the Compile/Compile With Tests commands will only compile the current file... how do other bundles handle this?

Always want to save the least possible number of items. Generally we want the user to explicitly save themselves, and only auto-save when the command would require it. When possible for running single files we can even use temporary files to prevent needing to save anything. Of course this isn't always possible depending on the compiler or reliance on relative files.

**Comment by carols10cents** [comment]
Looked through your changes finally, they all make sense!! Working on your suggestions now :)

**Comment by carols10cents** [comment]
Buttons are hard.

**Comment by carols10cents** [comment]
I'm assuming I should wait for https://github.com/textmate/textmate/pull/1305 to land and be released before making the shortcuts for, e.g. Compile and Cargo Build be the same.

**Comment by infininight** [comment]
Yeah, there will be two stages: First will be deploying the change in a nightly build, then deploying the change in a normal release. The nightly will happen relatively quickly, the normal will be probably a month or two. Should probably just wait for the nightly and tell people to update. Worst case they have they have to manually select the cargo commands for a short while.

**Pull request merged**
