### PR TITLE
Format: Automatically format on save using rustfmt

### PR DESCRIPTION
**Pull request by mkhl**

### CODE REVIEW

**Comment by rtsuk** [comment]
@carols10cents asked me to take a look at merging this. My only qualm is that this isn't a feature I'd want on by default, as it would make it hard to create patches to projects that aren't using rustfmt yet. Is there any way to make it optional?

**Comment by infininight** [comment]
Speaking from the TextMate side this is something I would desire as well. I don't want anything in the installable bundles to run by default for support and intent reasons.

**Comment by rtsuk** [comment]
OK, barring a convincing argument from @mkhl, I propose to add a format file command similar to the cargo format command I added in my pull request. Once it we can close this PR.

**Comment by mkhl** [comment]
Sounds good to me.

**Comment by carols10cents** [comment]
I'm sorry this has taken me so long to get to!!! The mentioned PR has been merged now, I agree that we should make this an on-demand thing in order to not require rust bundle users to have rustfmt installed.

**Pull request closed without merging**
